name: Generate Detailed Tech Blog with Gemini

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate blog markdown
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python .github/scripts/gen_blog.py

      - name: Commit and push blog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Add new blog post"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/williamcachamwri/blog-data.git HEAD:main

