name: Generate Detailed Tech Blog with Gemini

on:
  schedule:
    - cron: '*/5 * * * *'  # Mỗi 5 phút
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate blog markdown
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python .github/scripts/gen_blog.py

      - name: Check for changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit and push blog if changes detected
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .  # Ensure all files are added
          git commit -m "Add new blog post" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/williamcachamwri/blog-data.git HEAD:main
